package pl.patrykbober.bloomer.common.exception;

public enum ErrorCode {

    EMAIL_ALREADY_EXISTS,

    USER_NOT_FOUND,

    INVALID_ACCOUNT_CONFIRMATION_TOKEN,
    ACCOUNT_CONFIRMATION_TOKEN_EXPIRED,
    ACCOUNT_CONFIRMATION_TOKEN_ALREADY_USED,

}
