version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=bloomer
      - POSTGRES_PASSWORD=bloomer
      - POSTGRES_DB=bloomer
    ports:
      - '5433:5432'
    volumes:
      - bloomer-postgres-volume:/var/lib/postgresql/data

volumes:
  bloomer-postgres-volume:
