version: "3.9"

services:
  postgres-keycloak:
    image: postgres:14.1-alpine
    container_name: postgres-keycloak
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    #    ports:
    #      - '5433:5432'
    network_mode: host
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: bloomer
      POSTGRES_USER: bloomer
      POSTGRES_PASSWORD: bloomer
    ports:
      - '5433:5432'
    volumes:
      - bloomer-postgres-volume:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres-keycloak
    image: quay.io/keycloak/keycloak:21.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    network_mode: host
#    ports:
#      - '8080:8080'

volumes:
  keycloak-postgres-volume:
  bloomer-postgres-volume:
