server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs

spring:
  liquibase:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    private.key: classpath:key/bloomer.key
    public.key: classpath:key/bloomer.key.pub

    expiry:
      access_token: 3600 # 60 * 60
      refresh_token: 1209600 # 60 * 60 * 24 * 14
  account_confirmation:
    token:
      expiry: 86400 # 60 * 60 * 24
