server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloomer
    username: bloomer
    password: bloomer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

app:
  jwt:
    private.key: classpath:key/bloomer.key
    public.key: classpath:key/bloomer.key.pub

    expiry:
      access_token: 3600 # 60 * 60
      refresh_token: 1209600 # 60 * 60 * 24 * 14
