server:
  servlet:
    context-path: /api
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs

spring:
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bloomer
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  auth:
    keycloak:
      base-url: http://localhost:8080
      realm-name: bloomer
      client-id: bloomer-android
