spring:
  liquibase:
    enabled: false

app:
  jwt:
    private.key: classpath:key/bloomer.key
    public.key: classpath:key/bloomer.key.pub

    expiry:
      access_token: 3600 # 60 * 60
      refresh_token: 1209600 # 60 * 60 * 24 * 14
